export const PaketDatas = [
  {
    tipe: "Umrah",
    promo: true,
    judul: "Umrah Awal Musim",
    deskripsi:
      "Nikmati kesempatan luar biasa untuk beribadah di awal musim dengan **Paket Umrah 9 Hari** yang dirancang khusus untuk kenyamanan Anda. Dengan **akomodasi hotel dekat Masjid** di Makkah dan Madinah, Anda dapat lebih fokus pada ibadah tanpa harus berjalan jauh. Selain itu, paket ini juga mencakup **tour eksklusif di Madinah dan Makkah**, di mana Anda akan mengunjungi tempat-tempat bersejarah dan suci yang akan memperkaya pengalaman spiritual Anda. Seluruh perjalanan akan didukung oleh **tim profesional berpengalaman** yang siap membantu dan membimbing setiap langkah perjalanan Anda, memastikan ibadah umrah Anda berjalan lancar dan penuh makna. Bergabunglah dengan kami untuk memulai perjalanan suci yang akan membawa ketenangan dan kebahagiaan spiritual dalam hidup Anda.",
    total_harga: "IDR 27.500.000",
    durasi_hari: "09 Hari",
    tanggal: "2024-09-19",
    maskapai: "Oman Air",
    tujuan: ["Makkah & Madinah"],
    gambar: "/renew/paket/umrah-awal-musim.webp",
    bintang_hotel: 5,
    keberangkatan: "Jakarta",
    kursi_tersedia: "10 pax",
    masa_tunggu: "-",
    slug: "umrah-awal-musim",
    status_perjalanan: "-",
    harga_pp: "-",
  },
  {
    tipe: "Umrah",
    promo: true,
    judul: "Umrah 2x Jumat",
    deskripsi:
      "Nikmati pengalaman ibadah yang penuh berkah dengan Paket Umrah 2x Jumat selama 12 hari. Dengan akomodasi mewah di hotel bintang 5 di Makkah, Anda akan merasakan kenyamanan luar biasa selama perjalanan spiritual ini. Tidak hanya bisa menjalani dua kali Jumat di Tanah Suci, Anda juga akan diajak berkeliling dalam **tour gratis ke 6 tempat bersejarah** yang akan memperkaya pemahaman Anda tentang warisan Islam. Paket ini dirancang untuk memberikan keseimbangan sempurna antara ibadah dan wisata religi, semuanya didampingi oleh **tim berpengalaman** yang siap membimbing perjalanan Anda dari awal hingga akhir. Bergabunglah dengan ribuan alumni yang telah mempercayakan ibadah umrahnya kepada kami, dan rasakan pengalaman spiritual yang lebih bermakna dengan pelayanan terbaik kami.",
    total_harga: "IDR 35.000.000",
    durasi_hari: "12 Hari",
    tanggal: "2024-09-26",
    maskapai: "Saudi Airlines",
    tujuan: ["Jeddah"],
    gambar: "/renew/paket/umrah-2x-jumat.webp",
    bintang_hotel: 5,
    keberangkatan: "Jakarta",
    kursi_tersedia: "10 pax",
    masa_tunggu: "-",
    slug: "umrah-2x-jumat",
    status_perjalanan: "-",
    harga_pp: "-",
  },
  {
    tipe: "Umrah",
    promo: true,
    judul: "Umrah VIP",
    deskripsi:
      "Temukan pengalaman umrah tak terlupakan dengan Paket Umrah VIP yang menawarkan fleksibilitas dan kemewahan tanpa batas. Anda bisa memilih hari keberangkatan sesuai keinginan, dengan akomodasi mewah di hotel bintang 5 yang berada tepat di pelantaran Masjidil Haram dan Masjid Nabawi. Nikmati kenyamanan perjalanan dengan kursi pesawat kelas bisni, dan sesuaikan program ibadah maupun wisata Anda sesuai preferensi pribadi. Didukung oleh pelayanan eksklusif dari tim profesional kami, Anda bebas mengatur jadwal dan detail perjalanan agar sesuai dengan kebutuhan spiritual dan kenyamanan maksimal. Paket VIP ini dibuat khusus untuk Anda yang ingin merasakan pengalaman ibadah dengan sentuhan kemewahan dan kebebasan penuh.",
    total_harga: "IDR 50.000.000",
    durasi_hari: "By Request",
    tanggal: "By Request",
    maskapai: "By Request",
    tujuan: [],
    gambar: "/renew/paket/umrah-vip.webp",
    bintang_hotel: 5,
    keberangkatan: "By Request",
    kursi_tersedia: "By Request",
    masa_tunggu: "-",
    slug: "umrah-vip",
    status_perjalanan: "-",
    harga_pp: "-",
  },
  {
    tipe: "Haji",
    promo: false,
    judul: "Haji Plus",
    deskripsi: "-",
    total_harga: "USD 15.000",
    durasi_hari: "25 Hari",
    tanggal: "By Request",
    maskapai: "By Request",
    tujuan: [],
    gambar: "/renew/paket/haji-plus.webp",
    bintang_hotel: 5,
    keberangkatan: "Jakarta",
    kursi_tersedia: "By Request",
    masa_tunggu: "5-6 tahun",
    slug: "haji-plus",
    status_perjalanan: "-",
    harga_pp: "-",
  },
  {
    tipe: "Haji",
    promo: false,
    judul: "Haji Percepatan",
    deskripsi: "-",
    total_harga: "USD 20.000",
    durasi_hari: "25 Hari",
    tanggal: "By Request",
    maskapai: "By Request",
    tujuan: [],
    gambar: "/renew/paket/haji-percepatan.png",
    bintang_hotel: 5,
    keberangkatan: "Jakarta",
    kursi_tersedia: "By Kuota Pemerintah",
    masa_tunggu: "1 Tahun",
    slug: "haji-percepatan",
    status_perjalanan: "-",
    harga_pp: "-",
  },
  {
    tipe: "Halal",
    promo: false,
    judul: "Paket Halal Tour Turkey",
    deskripsi: "",
    total_harga: "-",
    durasi_hari: "By Request",
    tanggal: "By Request",
    maskapai: "By Request",
    tujuan: [
      "Istanbul",
      "Cappadocia",
      "Antalya",
      "Bodrum",
      "Ankara",
      "Izmir",
      "Gallipoli",
    ],
    gambar: "/renew/paket/halal-turkey.png",
    bintang_hotel: 5,
    keberangkatan: "By Request",
    kursi_tersedia: "By Request",
    masa_tunggu: "By Request",
    slug: "paket-halal-tour-turkey",
    status_perjalanan: "-",
    harga_pp: "-",
  },
  {
    tipe: "Halal",
    promo: false,
    judul: "Paket Halal Tour Maroko",
    deskripsi: "",
    total_harga: "-",
    durasi_hari: "By Request",
    tanggal: "By Request",
    maskapai: "By Request",
    tujuan: [
      "Meknes",
      "Asilah",
      "High Atlas",
      "Essaouira",
      "Chefchaoues",
      "Sahara Desert",
      "Rabat",
    ],
    gambar: "/renew/paket/halal-maroko.png",
    bintang_hotel: 5,
    keberangkatan: "By Request",
    kursi_tersedia: "By Request",
    masa_tunggu: "By Request",
    slug: "paket-halal-tour-maroko",
    status_perjalanan: "-",
    harga_pp: "-",
  },
];
